---
- name: Disable Defender completely
  ansible.windows.win_powershell:
    script: |
      New-ItemProperty -Path “HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender” -Name DisableAntiSpyware -Value 1 -PropertyType DWORD -Force