
- name: Nslooup splunk.common
  win_command: 'nslookup download.splunk.com'
  register: output

# - name: Debug nslookup
#   debug:
#     var: output

- name: copy Splunk UF to virtual host
  win_copy:
    src: ~/Downloads/splunkforwarder-8.0.2-a7f645ddaf91-x64-release.msi
    dest: C:\splunkuf.msi

- name: Install Splunk_UF MSI
  win_package:
    path: C:\splunkuf.msi
    arguments: 'WINEVENTLOG_SEC_ENABLE=0 WINEVENTLOG_SYS_ENABLE=0 WINEVENTLOG_APP_ENABLE=0 SPLUNKPASSWORD={{ splunk_admin_password }} AGREETOLICENSE=YES /quiet'

- name: Start Splunk
  win_service:
    name: SplunkForwarder
    state: started
